apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
  namespace: lab-devops
  labels:
    app: weather-api
spec:
  replicas: 2   # número de réplicas da aplicação
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: erickveiga/weather-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: OPENWEATHER_API_KEY
              value: "SUA_API_KEY_AQUI"
          resources: # opcional, boas práticas
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
