apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: lab-devops
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80        # Porta exposta pelo Service
      targetPort: 3000 # Porta do container
  type: NodePort       # pode trocar para LoadBalancer se estiver em cloud
