apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api-ingress
  namespace: lab-devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: weather.local     # domínio que você quer usar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-api-service
                port:
                  number: 80
